version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: we_dont_like_mongodb
      MYSQL_DATABASE: personalsbxtrovit
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: [ '--default-authentication-plugin=mysql_native_password' ]

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/personalsbxtrovit?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - db
    links:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

volumes:
  db-data:
